dist: trusty
language: python
python:
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install -e .
  - pip install flake8
script:
<<<<<<< HEAD
  - flake8 evodoc --count
=======
  - flake8 evodoc --count
>>>>>>> d6bb021d524da711576c36dab008a490fb7fcb25
