dist: trusty
language: python
python:
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install -e .
  - pip install flake8
script:
  - flake8 evodoc --count
