"""empty message

Revision ID: 275aa21e4333
Revises: 6734a785868e
Create Date: 2018-12-01 21:35:48.491517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275aa21e4333'
down_revision = '6734a785868e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
