"""empty message

Revision ID: 27dbc1b7b053
Revises: 8cc68a647c28
Create Date: 2018-12-18 01:37:15.458693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27dbc1b7b053'
down_revision = '8cc68a647c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contentType', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_column('contentType')

    # ### end Alembic commands ###
