"""empty message

Revision ID: 2c238b6a7bc7
Revises: 202817fcd206
Create Date: 2018-10-21 17:23:30.828162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c238b6a7bc7'
down_revision = '202817fcd206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_package_name'), ['name'])
        batch_op.create_unique_constraint(batch_op.f('uq_package_url'), ['url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_package_url'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_package_name'), type_='unique')

    # ### end Alembic commands ###
