"""empty message

Revision ID: 8cc68a647c28
Revises: 275aa21e4333
Create Date: 2018-12-04 00:30:44.885534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc68a647c28'
down_revision = '275aa21e4333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_to_module',
    sa.Column('used_in_module_id', sa.Integer(), nullable=False),
    sa.Column('dependency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['module.id'], name=op.f('fk_module_to_module_dependency_id_module')),
    sa.ForeignKeyConstraint(['used_in_module_id'], ['module.id'], name=op.f('fk_module_to_module_used_in_module_id_module')),
    sa.PrimaryKeyConstraint('used_in_module_id', 'dependency_id', name=op.f('pk_module_to_module'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_to_module')
    # ### end Alembic commands ###
